"""Phase 8: exchange order/fill audit trail and position linkage.

Revision ID: 20260806_0010
Revises: 20260804_0009
Create Date: 2026-08-06

Adds the persistence Phase 8 needs to talk to a venue safely:
``exchange_orders`` (one row per idempotency key, written before the order is
sent) and append-only ``exchange_fills`` (one row per venue execution).
``positions.exchange_order_id`` links a venue-opened position to its order the
same way ``positions.order_id`` links a paper-opened one.

Paper tables (``paper_orders``) are untouched.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260806_0010"
down_revision: Union[str, Sequence[str], None] = "20260804_0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ORDER_STATUSES = (
    "PENDING",
    "PARTIALLY_FILLED",
    "FILLED",
    "CANCELLED",
    "REJECTED",
    "UNKNOWN",
)


def upgrade() -> None:
    op.create_table(
        "exchange_orders",
        sa.Column(
            "id",
            sa.Uuid(),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        # Idempotency key: generated by us, sent to the venue, never reused.
        sa.Column("client_order_id", sa.Uuid(), nullable=False, unique=True),
        sa.Column("exchange_order_id", sa.Text(), nullable=True),
        sa.Column("adapter_name", sa.Text(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), sa.ForeignKey("wallets.id"), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("order_type", sa.Text(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("qty_requested", sa.Numeric(18, 8), nullable=False),
        sa.Column(
            "qty_filled",
            sa.Numeric(18, 8),
            nullable=False,
            server_default=sa.text("0"),
        ),
        # signal_price is the pre-trade estimate; avg_fill_price is authority.
        sa.Column("signal_price", sa.Numeric(18, 8), nullable=True),
        sa.Column("avg_fill_price", sa.Numeric(18, 8), nullable=True),
        sa.Column(
            "fee_paid",
            sa.Numeric(18, 8),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "fee_asset", sa.Text(), nullable=False, server_default=sa.text("'USDT'")
        ),
        sa.Column(
            "reduce_only",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column("leverage", sa.Numeric(9, 4), nullable=True),
        sa.Column(
            "position_id",
            sa.Uuid(),
            sa.ForeignKey("positions.id"),
            nullable=True,
        ),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("reject_code", sa.Text(), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column(
            "raw_response",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.CheckConstraint(
            "side IN ('BUY', 'SELL')", name="exchange_orders_side_check"
        ),
        sa.CheckConstraint(
            "order_type IN ('MARKET', 'LIMIT')",
            name="exchange_orders_type_check",
        ),
        sa.CheckConstraint(
            "intent IN ('OPEN', 'CLOSE')", name="exchange_orders_intent_check"
        ),
        sa.CheckConstraint(
            "status IN ("
            + ", ".join(f"'{s}'" for s in ORDER_STATUSES)
            + ")",
            name="exchange_orders_status_check",
        ),
        sa.CheckConstraint(
            "qty_requested > 0", name="exchange_orders_qty_requested_pos"
        ),
        sa.CheckConstraint(
            "qty_filled >= 0 AND qty_filled <= qty_requested",
            name="exchange_orders_qty_filled_bounds",
        ),
        sa.CheckConstraint(
            "qty_filled = 0 OR (avg_fill_price IS NOT NULL AND avg_fill_price > 0)",
            name="exchange_orders_fill_price_required",
        ),
        sa.CheckConstraint("fee_paid >= 0", name="exchange_orders_fee_nonneg"),
    )
    op.create_index(
        "idx_exchange_orders_wallet_id", "exchange_orders", ["wallet_id"]
    )
    op.create_index("idx_exchange_orders_status", "exchange_orders", ["status"])
    op.create_index(
        "idx_exchange_orders_created_at", "exchange_orders", ["created_at"]
    )
    op.create_index(
        "idx_exchange_orders_correlation_id",
        "exchange_orders",
        ["correlation_id"],
    )
    op.create_index(
        "idx_exchange_orders_position_id", "exchange_orders", ["position_id"]
    )

    op.create_table(
        "exchange_fills",
        sa.Column(
            "id",
            sa.Uuid(),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "exchange_order_row_id",
            sa.Uuid(),
            sa.ForeignKey("exchange_orders.id"),
            nullable=False,
        ),
        sa.Column("venue_fill_id", sa.Text(), nullable=True),
        sa.Column("qty_filled", sa.Numeric(18, 8), nullable=False),
        sa.Column("fill_price", sa.Numeric(18, 8), nullable=False),
        sa.Column(
            "fee_paid",
            sa.Numeric(18, 8),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "fee_asset", sa.Text(), nullable=False, server_default=sa.text("'USDT'")
        ),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_event",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.CheckConstraint("qty_filled > 0", name="exchange_fills_qty_pos"),
        sa.CheckConstraint("fill_price > 0", name="exchange_fills_price_pos"),
        sa.CheckConstraint("fee_paid >= 0", name="exchange_fills_fee_nonneg"),
    )
    op.create_index(
        "idx_exchange_fills_order_row_id",
        "exchange_fills",
        ["exchange_order_row_id"],
    )
    op.create_index(
        "idx_exchange_fills_timestamp", "exchange_fills", ["timestamp_utc"]
    )
    # Replayed websocket events must not double-count a venue execution.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_exchange_fills_venue_fill_id
        ON exchange_fills (exchange_order_row_id, venue_fill_id)
        WHERE venue_fill_id IS NOT NULL
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION exchange_fills_append_only()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION
                'exchange_fills is append-only: % not allowed',
                TG_OP;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_exchange_fills_append_only
        BEFORE UPDATE OR DELETE ON exchange_fills
        FOR EACH ROW
        EXECUTE FUNCTION exchange_fills_append_only();
        """
    )

    op.add_column(
        "positions",
        sa.Column("exchange_order_id", sa.Uuid(), nullable=True),
    )
    op.create_foreign_key(
        "positions_exchange_order_id_fkey",
        "positions",
        "exchange_orders",
        ["exchange_order_id"],
        ["id"],
    )
    op.create_unique_constraint(
        "positions_exchange_order_id_key", "positions", ["exchange_order_id"]
    )
    # A position is opened by exactly one venue: paper or exchange, never both.
    op.create_check_constraint(
        "positions_single_open_order_source",
        "positions",
        "NOT (order_id IS NOT NULL AND exchange_order_id IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(
        "positions_single_open_order_source", "positions", type_="check"
    )
    op.drop_constraint(
        "positions_exchange_order_id_key", "positions", type_="unique"
    )
    op.drop_constraint(
        "positions_exchange_order_id_fkey", "positions", type_="foreignkey"
    )
    op.drop_column("positions", "exchange_order_id")

    op.execute(
        "DROP TRIGGER IF EXISTS trg_exchange_fills_append_only ON exchange_fills"
    )
    op.execute("DROP FUNCTION IF EXISTS exchange_fills_append_only()")
    op.execute("DROP INDEX IF EXISTS uq_exchange_fills_venue_fill_id")
    op.drop_index("idx_exchange_fills_timestamp", table_name="exchange_fills")
    op.drop_index("idx_exchange_fills_order_row_id", table_name="exchange_fills")
    op.drop_table("exchange_fills")

    op.drop_index(
        "idx_exchange_orders_position_id", table_name="exchange_orders"
    )
    op.drop_index(
        "idx_exchange_orders_correlation_id", table_name="exchange_orders"
    )
    op.drop_index("idx_exchange_orders_created_at", table_name="exchange_orders")
    op.drop_index("idx_exchange_orders_status", table_name="exchange_orders")
    op.drop_index("idx_exchange_orders_wallet_id", table_name="exchange_orders")
    op.drop_table("exchange_orders")
